---
# This include_vars allows you to keep your vaulted variables outside of your main repo
# It assumes the PRIVATE_REPO environment variable is set to the path of your private repo
# On home-infra, this is done by firstrun.sh.
# However, this role will not break if you do not have these
- name: Include vaulted password file
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ lookup('env', 'PRIVATE_REPO') | default('~') }}/ansible-vault/{{ ansible_role_name }}-vars.yml"
      skip: true


- name: Configure admin user password
  ansible.builtin.uri:
    url: "{{ portainer_endpoint }}/users/admin/init"
    method: POST
    return_content: true
    body_format: json
    body: '{ "Username":"{{ admin_user }}", "Password":"{{ admin_password }}"}'
    status_code: 200, 409
    validate_certs: false
