---
# Fix Andre January 2026: Added the Endpoint ID to narrow the check to the requested endpoint only
- name: "Get stack information from Portainer for '{{ stack_name }}' on endpoint: {{ endpoint_id }}" # noqa: name[template]
  ansible.builtin.uri:
    # url: "{{ portainer_endpoint }}/stacks?filters={\"EndpointId\":{{ endpoint_id }}}"
    url: "{{ portainer_endpoint }}/stacks"
    method: GET
    headers:
      Authorization: "Bearer {{ jwt_token }}"
    validate_certs: false
  register: get_stack_response
  when: jwt_token is defined

- name: "Condense the stack-information into a fact"
  ansible.builtin.set_fact:
    stackinfo: "{{ get_stack_response.json | community.general.json_query(stack_query) | first | default({}) }}"
  vars:
    stack_query: "[?Name=='{{ stack_name }}'].{Name: Name, Id: Id, EndpointId: EndpointId}"

# In case we found info on this stack (stackinfo is set), but its EndpointId is not
# the endpoint that is requested, we are possibly dealing with an Orphaned stack,
# which is recoverable:
- name: "Associating orphaned '{{ stack_name }}' with: {{ endpoint_id }}" # noqa: name[template]
  ansible.builtin.uri:
    url: "{{ portainer_endpoint }}/stacks/{{ stackinfo.Id }}/associate?endpointId={{ endpoint_id }}&orphanedRunning=true"
    method: PUT
    headers:
      Authorization: "Bearer {{ jwt_token }}"
    validate_certs: false
  when:
    - jwt_token is defined
    - stackinfo.EndpointId | default(endpoint_id) != endpoint_id

- name: "Check if the stack already exists - {{ stack_name }}"
  ansible.builtin.set_fact:
    stack_not_exists: "{{ stackinfo == {} }}"
    existing_stack_id: "{{ stackinfo.Id | default() }}"

- name: "Creating a stack in Portainer by the name of {{ stack_name }}"
  ansible.builtin.uri:
    url: "{{ portainer_endpoint }}/stacks/create/standalone/string?endpointId={{ endpoint_id }}"
    method: POST
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ jwt_token }}"
    body_format: json
    body:
      env: "{{ stack_env }}"
      name: "{{ stack_name }}"
      fromAppTemplate: false
      stackFileContent: "{{ stack_compose }}"
    validate_certs: false
    timeout: 300 # Some stack creation can be quite time-consuming
    status_code:
      - 200
  register: create_stack_response
  when:
    - jwt_token is defined
    - stack_not_exists

- name: "Updating a stack in Portainer by the name of {{ stack_name }}"
  ansible.builtin.uri:
    url: "{{ portainer_endpoint }}/stacks/{{ existing_stack_id }}?endpointId={{ endpoint_id }}"
    method: PUT
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ jwt_token }}"
    body_format: json
    body:
      prune: false
      pullImage: false
      env: "{{ stack_env }}"
      stackFileContent: "{{ stack_compose }}"
    validate_certs: false
    timeout: 300 # Some stack creation can be quite time-consuming
  when:
    - jwt_token is defined
    - existing_stack_id != '0'
    - not stack_not_exists
    - stack_update

- name: Block for post stack creation
  when: post_create_handler != ''
  block:
    - name: "Register post-creation activities"
      ansible.builtin.import_tasks: "{{ post_create_handler or '../handlers/dummy_handler.yml' }}"
