---
# The main Portainer install is on the server that is also the 'homeserver' in the inventory.
# Additional servers are 'outpost' servers that get Portainer Agent installed and registered
# to the main Portainer instance.
# This file builds the required variable to set the endpoints
# Please not that the first endpoint is a local one. Adding it throught the API fails.
- name: Retrieve a list of already configured endpoints (environments) from Portainer
  ansible.builtin.uri:
    url: "{{ portainer_endpoint }}/endpoints"
    method: GET
    return_content: true
    validate_certs: false
    headers:
      Authorization: Bearer {{ (auth_token.content | from_json).jwt }}
  register: portainer_known_endpoints_raw
  when: not port_skip

- name: Save the already defined endpoints (environments) as fact
  ansible.builtin.set_fact:
    portainer_known_endpoints: "{{ portainer_known_endpoints_raw.json | map(attribute='Name') | list }}"
    portainer_known_endpoint_ids: "{{ portainer_known_endpoints_raw.json | map(attribute='Id') | list }}"
  when: not port_skip

- name: "Set info for this server as an endpoint, should always be id 1"
  ansible.builtin.set_fact:
    endpoints:
      - { name: "{{ inventory_hostname }}", id: 1, url: "", publicurl: "{{ ansible_facts['default_ipv4'].address }}" }

# Note that adding the id will not determine the endpoint's actual id!
# It is just there to preclude it being interpreted as the main (local) endpoint
# Bugfix 2026-03: the group-name should now be portainer_agent
# Bugfix 2026-03: only include the endpoints that are appropriate for this host (virtualization_role should be equal)
- name: Block to add Portainer Agents as endpoints
  block:
    - name: Add each Portainer Agent as an endpoint
      ansible.builtin.set_fact:
        endpoints: "{{ endpoints + [{'name': host, 'id': 2, 'url': 'tcp://' + hostvars[host].ansible_facts['default_ipv4'].address + ':9001', 'publicurl': hostvars[host].ansible_facts['default_ipv4'].address}] }}" # noqa: yaml[line-length]
      loop: "{{ groups['portainer_agent'] | default([]) }}"
      loop_control:
        loop_var: host
      when: hostvars[host].ansible_facts['virtualization_role'] == ansible_facts['virtualization_role']
