---
- name: Deploy Portainer Agent
  community.docker.docker_container:
    name: "portainer_agent"
    image: "portainer/agent:{{ portainer_agent_version }}"
    state: started
    detach: true
    restart_policy: always
    published_ports: "9001:9001"
    image_name_mismatch: "recreate"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
  delegate_to: "{{ agent_target }}"

- name: "Ensure the shared network 'reverse-proxy' exists on all outposts"
  community.docker.docker_network:
    name: reverse-proxy
    driver: bridge
    enable_ipv6: true
    state: present
    validate_certs: false
  delegate_to: "{{ agent_target }}"

# I define Portainer Agent mutually exclusive with main Portainer
- name: Remove erroneous Portainer main container
  community.docker.docker_container:
    name: portainer
    state: absent
    networks: []
    force_kill: true
  delegate_to: "{{ agent_target }}"
