---
# This include_vars allows you to keep your vaulted variables outside of your main repo
# It assumes the PRIVATE_REPO environment variable is set to the path of your private repo
# On home-infra, this is done by firstrun.sh.
# However, this role will not break if you do not have these
- name: Include vaulted password file
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ private_repo }}/{{ ansible_vault }}/{{ ansible_role_name }}-vars.yml"
      skip: true

- name: "Assert that we have at least one designated host for Portainer"
  ansible.builtin.assert:
    that:
      - hostvars[groups['portainer_server'][0]] is defined
    fail_msg: "You should have at least a portainer_server in your inventory"

- name: "Check the existence of jwt_token. If it is set this early in the role, it means we have a valid token still (multiple runs) and we can skip install"
  ansible.builtin.set_fact:
    port_skip: "{{ jwt_token is defined | bool }}"

# Call this role as follows:
# - name: "Include role to deploy homepage-stack to Portainer"
#  ansible.builtin.include_role:
#    name: waal70.portainer
#  vars:
#    stack_list:
#      - name: homepage
#        file: homepage.yml
#        endpointid: 2 # optional, defaults to 1
#        stack_update: true # optional, defaults to do_stack_update variable
#        env: {} # optional, defaults to default_env variable
#        dirs: [] # optional, list of directories to create before deploying stack
#        post_handler: '' # optional, path to task file to run after stack creation
#
# This role should be run on the homeserver only, as it assumes that the Portainer
# instance is running there. It will however also install Portainer Agent on any
# outpost servers defined in the inventory and manage stack installs on that satellite

- name: "Include clean-up tasks"
  ansible.builtin.include_tasks: clean-up.yml
  when: not port_skip

- name: "Include installation tasks for main Portainer"
  ansible.builtin.include_tasks: install.yml
  when:
    - not port_skip
    - "'portainer_server' in group_names"

- name: "Ensure Portainer Agents are installed on all hosts in portainer_agent"
  ansible.builtin.include_tasks: install-agent.yml
  vars:
    agent_target: "{{ item }}"
  with_items:
    - "{{ groups['portainer_agent'] | default([]) }}"
  when:
    - not port_skip
    - hostvars[item].ansible_facts['virtualization_role'] | default('no_facts_gathered') == ansible_facts['virtualization_role']

# The main install leaves us with portainer_endpoint, but if we are re-running this role
# that install is skipped. So we set the URL for Portainer always here:
# Please note that it will take the first host from the portainer_server group, so if you have more than one, change this code!
- name: "Set fact for Portainer management URL"
  ansible.builtin.set_fact:
    portainer_endpoint: "https://{{ hostvars[item].ansible_facts['default_ipv4'].address }}:{{ host_port }}/api"
  with_items:
    - "{{ groups['portainer_server'] | default([]) }}"
  when:
    - portainer_endpoint is not defined
    - hostvars[item].ansible_facts['virtualization_role'] | default('no_facts_gathered') == ansible_facts['virtualization_role']
    - not port_skip

- name: "Login with username/password to generate authentication token, user: {{ admin_user }}"
  ansible.builtin.uri:
    url: "{{ portainer_endpoint }}/auth"
    method: POST
    return_content: true
    body_format: json
    body: '{"Username": "{{ admin_user }}", "Password": "{{ admin_password }}"}'
    validate_certs: false
    status_code:
      - 200
  register: auth_token
  when: admin_user and admin_password is defined

- name: "Get JWT token from authentication response"
  ansible.builtin.set_fact:
    jwt_token: "{{ auth_token.json.jwt }}"

# Primary portainer instance is one (1) endpoint
# Other endpoints are all the hosts in the portainer_agent group
- name: "Include tasks to determine the list of existing endpoints"
  ansible.builtin.include_tasks: get_endpoints.yml
  when: not port_skip

- name: Include tasks to add Portainer Agents for main node (=homeserver) only
  ansible.builtin.include_tasks: set_endpoints.yml
  when:
    - endpoints is not none
    - not port_skip

- name: "Inform the user of the combination of variables"
  ansible.builtin.debug:
    msg: "Requested actions for {{ portainer_known_endpoints[endpoint_idx] }}, while running on host {{ inventory_hostname }}"

- name: Incude tasks to add stacks to Portainer
  ansible.builtin.include_tasks: stacklooper.yml
  when:
    - stack_list is defined
    - stack_list | length > 0
